// Browser-side `WalletBackend` that proxies signing through the cloud
// pairing relay on `agentic-signer.com/api/pair/*` (see
// `apps/render-web/src/cloud/pairingHandler.ts`). Used by the Tauri
// desktop when the user picks Phantom or Solflare from the QR step — the
// wallet itself runs in the phone's in-app browser, registers with the
// relay via POST /api/pair/:uuid/host, and the desktop adopts it via this
// backend.
//
// Sibling of the already-shipped `remoteBridgeBackend.ts` (which targets
// the local Tauri bridge for the Browser-extension method). Same
// `WalletBackend` interface, different transport.

import {
  ProtocolError,
  type AdapterCapabilities,
  type ApprovalResource,
  type SigningRequest,
  type SigningRequestId,
  type WalletBackend,
} from '@solana-agent-wallet-adapter/core';

export interface RemoteRelayBackendOptions {
  /** Base URL of the deployed wallet-host backend that exposes the
   *  pairing endpoints. In production that's `https://agentic-signer.com`. */
  baseUrl: string;
  /** UUID v4 generated by the desktop and embedded in the wallet's
   *  universal-link redirect. Authenticates the desktop's reads/writes
   *  against the matching pairing record. */
  pairingUuid: string;
}

export class RemoteRelayBackend implements WalletBackend {
  private readonly baseUrl: string;
  private readonly pairingUuid: string;

  constructor(options: RemoteRelayBackendOptions) {
    this.baseUrl = options.baseUrl.endsWith('/') ? options.baseUrl.slice(0, -1) : options.baseUrl;
    this.pairingUuid = options.pairingUuid;
  }

  async capabilities(): Promise<AdapterCapabilities> {
    const host = await this.request<{
      address: string;
      capabilities: AdapterCapabilities;
      walletName: string;
    } | null>(`/host`, { method: 'GET' });
    if (!host) {
      throw new ProtocolError(
        'unauthorized',
        'Wallet host not yet registered on the pairing relay.',
      );
    }
    return { ...host.capabilities, address: host.address };
  }

  async getAddress(): Promise<string> {
    const capabilities = await this.capabilities();
    if (!capabilities.address) {
      throw new ProtocolError(
        'unauthorized',
        'No wallet address on the pairing record — open the wallet host on your phone first.',
      );
    }
    return capabilities.address;
  }

  async submit(request: SigningRequest): Promise<ApprovalResource> {
    return this.request<ApprovalResource>(`/submit`, {
      method: 'POST',
      body: JSON.stringify({ request }),
    });
  }

  async poll(requestId: SigningRequestId): Promise<ApprovalResource> {
    return this.request<ApprovalResource>(`/submit/${encodeURIComponent(requestId)}`, {
      method: 'GET',
    });
  }

  /** The relay has no cancellation primitive — abandoned requests expire
   *  by themselves via the TTL sweeper. No-op satisfies the WalletBackend
   *  optional method contract. */
  async cancel(_requestId: SigningRequestId): Promise<void> {
    void _requestId;
  }

  private async request<T = unknown>(path: string, init: RequestInit): Promise<T> {
    const url = `${this.baseUrl}/api/pair/${encodeURIComponent(this.pairingUuid)}${path}`;
    const headers = new Headers(init.headers);
    if (init.body !== undefined && !headers.has('content-type')) {
      headers.set('content-type', 'application/json');
    }
    let response: Response;
    try {
      response = await fetch(url, { ...init, headers });
    } catch (err) {
      throw new ProtocolError(
        'wallet_unreachable',
        `Pairing relay unreachable: ${err instanceof Error ? err.message : String(err)}`,
      );
    }
    if (response.status === 404) {
      // Host not yet registered → caller (typically a pairing poll) treats
      // this as "keep waiting" rather than a hard failure.
      throw new ProtocolError('unauthorized', 'Pairing record not found.');
    }
    const payload = (await response.json().catch(() => ({}))) as unknown;
    if (!response.ok) {
      const message = extractError(payload) ?? `Relay returned ${response.status}.`;
      throw new ProtocolError('wallet_unreachable', message);
    }
    return payload as T;
  }
}

function extractError(payload: unknown): string | null {
  if (payload && typeof payload === 'object') {
    const obj = payload as Record<string, unknown>;
    if (typeof obj.error === 'string') return obj.error;
    if (typeof obj.message === 'string') return obj.message;
  }
  return null;
}
